### ISSUE TITLE
Installing the Addon hiddes the "marked" Tag from the sidebar

### ISSUE THREAD

**Issue by Weyaaron** [glutanimate/hierarchical-tags#1]
#### Problem description
Using this addon hiddes the "marked" Tag from view in the Tag-Sidebar. I have not tested for other tags.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

Version 2.1.15 (442df9d6)
Qt 5.14.1 PyQt 5.14.1

##### If you are using Anki 2.1

```
Anki 2.1.15 (442df9d6) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=False ao=True sv=1

Add-ons:

Search and Replace Tags (disabled)
Night Mode
AnkiConnect
Hierarchical Tags 2  Anki 2117 support
Merge Duplicate Cards
Set Font Size
```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Arch Linux
- version: -

**Comment by glutanimate** [comment]
Hi! Sorry for taking a while to respond (super busy as always).

I wanted to thank you for the detailed bug report! I'd completely missed the fact that both `marked` and `suspended`  would no longer appear in the sidebar (because I use the Customize Sidebar add-on).

For a quick background on what was going on here: Anki 2.0 used to treat both the `marked` and `leech` tag in a special way and add them to the top of the sidebar. In 2.1 that's no longer the case: They are relegated to regular tags. Hierarchical Tags' implementation, however, was still expecting that special treatment, and so it would skip adding these tags to the sidebar.

In any case, I've updated the add-on to properly handle both tags now. The fix should be live on AnkiWeb in a few minutes.

Thanks again for your help with this!
